// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09eAFZ7gBCtMx65Pc7FRTH-3vXR1qFnA',
    appId: '1:633300206578:web:922517040aedff2b8b616b',
    messagingSenderId: '633300206578',
    projectId: 'pamphere-f2557',
    authDomain: 'pamphere-f2557.firebaseapp.com',
    storageBucket: 'pamphere-f2557.appspot.com',
    measurementId: 'G-JV43199ZBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIXnl1V_t590uwnnUuC7zhqk6QYBHoFXA',
    appId: '1:633300206578:android:d3d8bdc455c422448b616b',
    messagingSenderId: '633300206578',
    projectId: 'pamphere-f2557',
    storageBucket: 'pamphere-f2557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLbw-Oc9r2K82YZ2e-ZpLYGt98jS-ZM1A',
    appId: '1:633300206578:ios:e5ca30217c75ae398b616b',
    messagingSenderId: '633300206578',
    projectId: 'pamphere-f2557',
    storageBucket: 'pamphere-f2557.appspot.com',
    iosBundleId: 'com.example.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLbw-Oc9r2K82YZ2e-ZpLYGt98jS-ZM1A',
    appId: '1:633300206578:ios:17767f46697d0e238b616b',
    messagingSenderId: '633300206578',
    projectId: 'pamphere-f2557',
    storageBucket: 'pamphere-f2557.appspot.com',
    iosBundleId: 'com.example.customer.RunnerTests',
  );
}
